// DEV-ONLY preview fixtures for the admin redesign harness. Not shipped.
import type { NannyProfile, ParentRequest } from '@/core/types';
import type { Booking } from '@/services/booking';
import type { AdminActionEntry } from '@/components/admin/AdminJournalTab';

const day = 24 * 60 * 60 * 1000;
const now = Date.now();

const P = (id: string, w = 256) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${w}&q=80`;

export const mockNannies = [
  {
    id: 'nanny-maria-01',
    type: 'nanny',
    name: 'Мария Соколова',
    photo: P('1494790108377-be9c29b29330'),
    city: 'Москва',
    district: 'Хамовники',
    metro: 'Парк культуры',
    experience: '8',
    expectedRate: '1 200 ₽/час',
    childAges: ['1-3', '3-7'],
    skills: ['раннее развитие', 'первая помощь', 'английский'],
    about: 'Спокойная, опытная няня. Работала в двух семьях по 3+ года.',
    contact: '+7 916 000-00-01',
    isVerified: true,
    video: 'https://example.com/video/maria.webm',
    createdAt: now - 2 * day,
    schedule: 'Будни 9:00–18:00',
    documents: [
      { type: 'passport', status: 'verified', aiConfidence: 96, aiNotes: 'Паспорт распознан, данные совпадают.', fileName: 'passport.pdf', fileDataUrl: 'data:application/pdf;base64,AAAA' },
      { type: 'medical_book', status: 'verified', aiConfidence: 91, aiNotes: 'Медкнижка действительна.', fileName: 'med.pdf', fileDataUrl: 'data:application/pdf;base64,AAAA' },
      { type: 'resume', status: 'verified', aiConfidence: 88, aiNotes: 'Резюме распознано.', fileName: 'cv.pdf', fileDataUrl: 'data:application/pdf;base64,AAAA' },
    ],
    softSkills: {
      dominantStyle: 'Заботливый-структурный',
      summary: 'Сочетает тепло и режим.',
      moderationSummary: 'Высокая эмпатия, чёткие границы. Хорошо для младенцев.',
      method: 'assessment_v2',
      coverage: 0.92,
      signals: [
        { signal: 'empathy_first', direction: 'positive', strength: 0.9, evidence: [] },
        { signal: 'safety_priority', direction: 'positive', strength: 0.85, evidence: [] },
      ],
    },
    reviews: [
      { authorName: 'Семья Ивановых', rating: 5, text: 'Дети её обожают, всегда на связи.' },
      { authorName: 'Семья П.', rating: 5, text: 'Очень внимательная и пунктуальная.' },
    ],
  },
  {
    id: 'nanny-olga-02',
    type: 'nanny',
    name: 'Ольга Петрова',
    photo: P('1438761681033-6461ffad8d80'),
    city: 'Москва',
    district: 'Сокол',
    experience: '4',
    expectedRate: '900 ₽/час',
    childAges: ['3-7'],
    skills: ['прогулки', 'творчество'],
    about: 'Энергичная, любит активные игры.',
    contact: '+7 916 000-00-02',
    isVerified: false,
    createdAt: now - 6 * 3600 * 1000,
    schedule: 'Гибкий график',
    documents: [
      { type: 'passport', status: 'pending', aiConfidence: 64, aiNotes: 'Низкое качество скана, нужна ручная проверка.', fileName: 'pass.jpg', fileDataUrl: 'data:image/png;base64,iVBORw0KGgo=' },
    ],
    softSkills: {
      dominantStyle: 'Игровой',
      summary: 'Активная, инициативная.',
      moderationSummary: 'Энергичная; стоит уточнить отношение к режиму.',
      method: 'assessment_v2',
      coverage: 0.7,
      signals: [{ signal: 'low_structure_preference', direction: 'watch', strength: 0.6, evidence: [] }],
    },
    reviews: [],
  },
  {
    id: 'nanny-elena-03',
    type: 'nanny',
    name: 'Елена Кузнецова',
    city: 'Москва',
    district: 'Митино',
    experience: '2',
    childAges: ['1-3'],
    skills: ['грудничок'],
    about: 'Недавно заполнила анкету, документы не загружены.',
    contact: '+7 916 000-00-03',
    isVerified: false,
    createdAt: now - 1 * 3600 * 1000,
    documents: [],
    reviews: [],
  },
  {
    id: 'nanny-anna-04',
    type: 'nanny',
    name: 'Анна Морозова',
    photo: P('1573496359142-b8d87734a5a2'),
    city: 'Москва',
    district: 'Тверской',
    metro: 'Маяковская',
    experience: '11',
    expectedRate: '1 500 ₽/час',
    childAges: ['0-1', '1-3'],
    skills: ['грудничок', 'медицинское образование', 'сон по режиму'],
    about: 'Медсестра в прошлом, специализируется на малышах.',
    contact: '+7 916 000-00-04',
    isVerified: true,
    createdAt: now - 9 * day,
    schedule: 'Будни, возможны выходные',
    documents: [
      { type: 'passport', status: 'verified', aiConfidence: 94, aiNotes: 'OK.', fileName: 'p.pdf', fileDataUrl: 'data:application/pdf;base64,AAAA' },
      { type: 'medical_book', status: 'rejected', aiConfidence: 40, aiNotes: 'Истёк срок действия.', fileName: 'm.pdf', fileDataUrl: 'data:application/pdf;base64,AAAA' },
      { type: 'education_document', status: 'pending', aiConfidence: 72, aiNotes: 'Диплom медсестры, проверяем.', fileName: 'edu.pdf' },
    ],
    softSkills: {
      dominantStyle: 'Медицинский-внимательный',
      summary: 'Высокий контроль безопасности.',
      moderationSummary: 'Сильная в безопасности; тёплая, но сдержанная.',
      method: 'assessment_v2',
      coverage: 0.95,
      signals: [
        { signal: 'safety_priority', direction: 'positive', strength: 0.95, evidence: [] },
        { signal: 'transparent_reporting', direction: 'positive', strength: 0.8, evidence: [] },
      ],
    },
    reviews: [{ authorName: 'Семья Смирновых', rating: 5, text: 'Спокойны за малыша.' }],
  },
] as unknown as NannyProfile[];

export const mockParents = [
  {
    id: 'parent-0001',
    type: 'parent',
    status: 'new',
    city: 'Москва',
    district: 'Хамовники',
    childAge: '3 года',
    schedule: 'Будни 16:00–20:00',
    budget: 'до 1 200 ₽/час',
    requirements: ['спокойный подход', 'забрать из сада', 'прогулки'],
    comment: 'Нужна няня на вторую половину дня.',
    requesterEmail: 'family1@example.com',
    createdAt: now - 3 * 3600 * 1000,
    updatedAt: now - 3 * 3600 * 1000,
    changeLog: [],
  },
  {
    id: 'parent-0002',
    type: 'parent',
    status: 'in_review',
    city: 'Москва',
    district: 'Сокол',
    childAge: '1 год',
    schedule: 'Полный день',
    budget: 'до 1 500 ₽/час',
    requirements: ['опыт с грудничками', 'медкнижка'],
    comment: 'Выходим на работу через месяц.',
    requesterEmail: 'family2@example.com',
    createdAt: now - 2 * day,
    updatedAt: now - 1 * day,
    changeLog: [{ type: 'resubmitted', note: 'Семья дополнила требования', at: now - 1 * day }],
  },
  {
    id: 'parent-0003',
    type: 'parent',
    status: 'approved',
    city: 'Москва',
    childAge: '5 лет',
    schedule: 'Будни утром',
    budget: 'до 1 000 ₽/час',
    requirements: ['английский'],
    comment: '',
    requesterEmail: 'family3@example.com',
    createdAt: now - 5 * day,
    updatedAt: now - 4 * day,
    changeLog: [],
  },
  {
    id: 'parent-0004',
    type: 'parent',
    status: 'rejected',
    city: 'Москва',
    childAge: '7 лет',
    schedule: 'Выходные',
    budget: 'до 800 ₽/час',
    requirements: [],
    comment: 'Только выходные.',
    requesterEmail: 'family4@example.com',
    createdAt: now - 8 * day,
    updatedAt: now - 7 * day,
    changeLog: [],
  },
  {
    id: 'parent-0005',
    type: 'parent',
    status: 'new',
    city: 'Москва',
    district: 'Пресненский',
    childAge: '2 года',
    schedule: 'Будни 14:00–19:00',
    budget: 'до 1 100 ₽/час',
    requirements: ['опыт от 3 лет'],
    comment: 'Спокойно если опытная.',
    createdAt: now - 5 * day,
    updatedAt: now - 5 * day,
    changeLog: [],
  },
  {
    id: 'parent-0006',
    type: 'parent',
    status: 'payment_pending',
    city: 'Москва',
    district: 'Раменки',
    childAge: '4 года',
    schedule: 'Будни утром',
    budget: 'до 1 300 ₽/час',
    requirements: [],
    comment: '',
    requesterEmail: 'family6@example.com',
    createdAt: now - 1 * day,
    updatedAt: now - 12 * 3600 * 1000,
    changeLog: [],
  },
] as unknown as ParentRequest[];

export const mockBookings = [
  { id: 'bk-1', parent_id: 'parent-0003', nanny_id: 'nanny-maria-01', status: 'confirmed', createdAt: now - 2 * day, date: now + 1 * day, amount: '6 000 ₽' },
  { id: 'bk-2', parent_id: 'parent-0002', nanny_id: 'nanny-anna-04', status: 'pending', createdAt: now - 1 * day, date: now + 3 * day, amount: '9 000 ₽' },
  { id: 'bk-3', parent_id: 'parent-0001', nanny_id: 'nanny-maria-01', status: 'completed', createdAt: now - 12 * day, date: now - 5 * day, amount: '5 500 ₽' },
] as unknown as Booking[];

export const mockActionFeed = [
  { action: 'workflow_success', at: now - 600000, kind: 'success', message: 'Профиль няни подтверждён', meta: { message: 'Профиль няни подтверждён' } },
  { action: 'clear_test', at: now - 3600000, message: 'Удалены тестовые записи', meta: {} },
  { action: 'booking_status_change', at: now - 7200000, meta: { id: 'bk-2', status: 'confirmed' } },
  { action: 'workflow_error', at: now - 9000000, kind: 'error', message: 'Не удалось отправить уведомление', meta: { message: 'Не удалось отправить уведомление' } },
] as unknown as AdminActionEntry[];
