-- Prod baseline as of 2026-03-22.
-- Generated by concatenating previously shipped migrations after normalizing
-- away duplicate daily version prefixes that broke Supabase migration history.

-- RLHF feedback table for matching quality improvement
-- Migration: create_matching_outcomes
-- Date: 2026-03-11

CREATE TYPE matching_outcome_type AS ENUM ('hired', 'rejected', 'ghosted');

CREATE TABLE matching_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nanny_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  outcome matching_outcome_type NOT NULL,
  feedback_text TEXT,
  score_at_match FLOAT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for analytics queries
CREATE INDEX idx_matching_outcomes_parent ON matching_outcomes(parent_id);
CREATE INDEX idx_matching_outcomes_nanny ON matching_outcomes(nanny_id);
CREATE INDEX idx_matching_outcomes_outcome ON matching_outcomes(outcome);
CREATE INDEX idx_matching_outcomes_created ON matching_outcomes(created_at);

-- RLS
ALTER TABLE matching_outcomes ENABLE ROW LEVEL SECURITY;

-- Parents can insert their own feedback
CREATE POLICY "Parents can insert own feedback"
  ON matching_outcomes FOR INSERT
  WITH CHECK (auth.uid() = parent_id);

-- Parents can view their own feedback
CREATE POLICY "Parents can view own feedback"
  ON matching_outcomes FOR SELECT
  USING (auth.uid() = parent_id);

-- Nannies can view feedback about them
CREATE POLICY "Nannies can view feedback about them"
  ON matching_outcomes FOR SELECT
  USING (auth.uid() = nanny_id);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_matching_outcomes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_matching_outcomes_updated_at
  BEFORE UPDATE ON matching_outcomes
  FOR EACH ROW
  EXECUTE FUNCTION update_matching_outcomes_updated_at();

COMMENT ON TABLE matching_outcomes IS 'RLHF feedback: outcome of parent-nanny matching for model training';
-- Create chat_threads table
CREATE TABLE IF NOT EXISTS chat_threads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create chat_participants table
CREATE TABLE IF NOT EXISTS chat_participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id UUID REFERENCES chat_threads(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create chat_messages table
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id UUID REFERENCES chat_threads(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Turn on Row Level Security
ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Policies for chat_threads
CREATE POLICY "Users can create threads" ON chat_threads FOR INSERT TO authenticated WITH CHECK (auth.uid() = family_id);
CREATE POLICY "Users can view their threads" ON chat_threads FOR SELECT TO authenticated USING (auth.uid() = family_id);

-- Policies for chat_participants
CREATE POLICY "Users can insert participants" ON chat_participants FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view participants" ON chat_participants FOR SELECT TO authenticated USING (user_id = auth.uid());

-- Policies for chat_messages
-- Check if user is participant or family_id of the thread
CREATE POLICY "Users can insert messages" ON chat_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can view messages" ON chat_messages FOR SELECT TO authenticated USING (
    thread_id IN (
        SELECT id FROM chat_threads WHERE family_id = auth.uid()
    )
);

-- Realtime publication for chat_messages
ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;
-- Creating the AI-Native Support Engine Tables

-- 1. Support Tickets (Context & Sentiment Tracking)
CREATE TABLE IF NOT EXISTS support_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL, -- Reference to the parent
    nanny_id UUID, -- Contextual nanny (if the conversation is about a specific match)
    match_id UUID, -- Reference to the specific match outcome
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'human_escalated')),
    sentiment_score FLOAT DEFAULT 0.0, -- Tracks emotional state (-1.0 to 1.0)
    summary TEXT, -- AI-generated summary of the problem
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Support Messages (The actual dialogue)
CREATE TABLE IF NOT EXISTS support_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID REFERENCES support_tickets(id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL CHECK (sender_type IN ('user', 'ai_concierge', 'human_agent')),
    sender_id UUID, -- For user or human agent
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Turn on Row Level Security
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;

-- Policies for support_tickets
CREATE POLICY "tickets_insert" ON support_tickets FOR INSERT TO authenticated WITH CHECK (auth.uid() = family_id);
CREATE POLICY "tickets_select" ON support_tickets FOR SELECT TO authenticated USING (auth.uid() = family_id);

-- Policies for support_messages
CREATE POLICY "msg_insert" ON support_messages FOR INSERT TO authenticated WITH CHECK (true); -- User can insert
CREATE POLICY "msg_select" ON support_messages FOR SELECT TO authenticated USING (true); -- In a real app, join with support_tickets

-- Turn on realtime for admin panel
ALTER PUBLICATION supabase_realtime ADD TABLE support_tickets;
ALTER PUBLICATION supabase_realtime ADD TABLE support_messages;
-- ============================================
-- SHIELD 3: Bulletproof RLS — all UUID columns
-- APPLIED: 2026-03-13
-- ============================================

-- 1. NANNIES
DROP POLICY IF EXISTS "nannies_owner" ON nannies;
DROP POLICY IF EXISTS "nannies_public_read" ON nannies;
DROP POLICY IF EXISTS "nannies_read_authenticated" ON nannies;
DROP POLICY IF EXISTS "nannies_admin_write" ON nannies;

CREATE POLICY "nannies_read_authenticated" ON nannies
  FOR SELECT USING (true);

CREATE POLICY "nannies_admin_write" ON nannies
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');


-- 2. PARENTS (user_id = UUID FK → auth.users)
DROP POLICY IF EXISTS "parents_owner" ON parents;
DROP POLICY IF EXISTS "parents_own_read" ON parents;
DROP POLICY IF EXISTS "parents_own_write" ON parents;
DROP POLICY IF EXISTS "parents_own_update" ON parents;
DROP POLICY IF EXISTS "parents_own_delete" ON parents;

CREATE POLICY "parents_own_read" ON parents
  FOR SELECT USING (auth.uid() = user_id OR auth.role() = 'service_role');

CREATE POLICY "parents_own_write" ON parents
  FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.role() = 'service_role');

CREATE POLICY "parents_own_update" ON parents
  FOR UPDATE USING (auth.uid() = user_id OR auth.role() = 'service_role');

CREATE POLICY "parents_own_delete" ON parents
  FOR DELETE USING (auth.uid() = user_id OR auth.role() = 'service_role');


-- 3. SUPPORT_TICKETS (family_id = UUID)
DROP POLICY IF EXISTS "tickets_insert" ON support_tickets;
DROP POLICY IF EXISTS "tickets_select" ON support_tickets;
DROP POLICY IF EXISTS "tickets_own_or_admin" ON support_tickets;
DROP POLICY IF EXISTS "tickets_insert_own" ON support_tickets;
DROP POLICY IF EXISTS "tickets_admin_modify" ON support_tickets;
DROP POLICY IF EXISTS "tickets_admin_delete" ON support_tickets;

CREATE POLICY "tickets_own_or_admin" ON support_tickets
  FOR SELECT USING (auth.uid() = family_id OR auth.role() = 'service_role');

CREATE POLICY "tickets_insert_own" ON support_tickets
  FOR INSERT WITH CHECK (auth.uid() = family_id OR auth.role() = 'service_role');

CREATE POLICY "tickets_admin_modify" ON support_tickets
  FOR UPDATE USING (auth.role() = 'service_role');

CREATE POLICY "tickets_admin_delete" ON support_tickets
  FOR DELETE USING (auth.role() = 'service_role');


-- 4. SUPPORT_MESSAGES (ticket_id = UUID FK)
DROP POLICY IF EXISTS "msg_insert" ON support_messages;
DROP POLICY IF EXISTS "msg_select" ON support_messages;
DROP POLICY IF EXISTS "messages_own_ticket" ON support_messages;
DROP POLICY IF EXISTS "messages_insert" ON support_messages;

CREATE POLICY "messages_own_ticket" ON support_messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM support_tickets st
      WHERE st.id = support_messages.ticket_id
        AND st.family_id = auth.uid()
    ) OR auth.role() = 'service_role'
  );

CREATE POLICY "messages_insert" ON support_messages
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM support_tickets st
      WHERE st.id = support_messages.ticket_id
        AND st.family_id = auth.uid()
    ) OR auth.role() = 'service_role'
  );


-- 5. PHONE_OTPS
ALTER TABLE IF EXISTS phone_otps ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "otps_service_only" ON phone_otps;

CREATE POLICY "otps_service_only" ON phone_otps
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');


-- 6. MATCHING_OUTCOMES
ALTER TABLE IF EXISTS matching_outcomes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "outcomes_service_only" ON matching_outcomes;

CREATE POLICY "outcomes_service_only" ON matching_outcomes
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
-- ============================================
-- Security Audit Log — tracks auth events
-- ============================================
CREATE TABLE IF NOT EXISTS security_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type TEXT NOT NULL,       -- 'otp_sent', 'otp_verified', 'otp_failed', 'login', 'tma_validated', 'rate_limited'
    ip_address TEXT,
    phone TEXT,                     -- masked: +7***1234
    user_id TEXT,
    tma_user_id BIGINT,            -- Telegram user ID if from TMA
    details JSONB DEFAULT '{}',    -- extra context
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Only service_role can access (API writes via service key)
ALTER TABLE security_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_service_only" ON security_audit_log;
CREATE POLICY "audit_service_only" ON security_audit_log
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_audit_event_type ON security_audit_log(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON security_audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_ip ON security_audit_log(ip_address);
-- ============================================
-- MATCHING EVOLUTION — Self-Evolving Infrastructure
-- Этап 0: Shadow Mode + Dynamic Weights
-- Этап 1: Insights RAG
-- APPLIED: 2026-03-14
-- ============================================

-- 1. Dynamic Weights Table (Bayesian weight storage)
CREATE TABLE IF NOT EXISTS matching_weights (
  factor TEXT PRIMARY KEY,
  weight FLOAT NOT NULL,
  prior_weight FLOAT NOT NULL,
  confidence FLOAT DEFAULT 0.5,
  sample_count INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Seed with current hardcoded weights
INSERT INTO matching_weights (factor, weight, prior_weight) VALUES
  ('base', 40, 40),
  ('verification', 12, 12),
  ('childAge', 10, 10),
  ('schedule', 6, 6),
  ('requirementMatch', 6, 6),
  ('mirrorMax', 18, 18),
  ('softSkillsMax', 8, 8),
  ('qualityPremium', 10, 10),
  ('qualityGood', 6, 6),
  ('nannySharing', 8, 8),
  ('familyStyleMatch', 10, 10),
  ('disciplineMatch', 6, 6),
  ('communicationMatch', 6, 6),
  ('stressResponseMatch', 6, 6),
  ('pcmMatch', 6, 6),
  ('growthPerNeed', 6, 6),
  ('growthMax', 12, 12)
ON CONFLICT (factor) DO NOTHING;

-- 2. Learned Insights Table (RAG for System Prompt)
CREATE TABLE IF NOT EXISTS matching_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_text TEXT NOT NULL,
  segment TEXT DEFAULT 'all',
  correlation FLOAT,
  sample_count INT DEFAULT 0,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Extend matching_outcomes with shadow scoring columns
ALTER TABLE matching_outcomes ADD COLUMN IF NOT EXISTS
  heuristic_score FLOAT;
ALTER TABLE matching_outcomes ADD COLUMN IF NOT EXISTS
  shadow_score FLOAT;
ALTER TABLE matching_outcomes ADD COLUMN IF NOT EXISTS
  weight_snapshot JSONB;
ALTER TABLE matching_outcomes ADD COLUMN IF NOT EXISTS
  factors JSONB;
ALTER TABLE matching_outcomes ADD COLUMN IF NOT EXISTS
  explore_flag BOOLEAN DEFAULT false;

-- 4. RLS — service_role only for weights and insights
ALTER TABLE matching_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE matching_insights ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'matching_weights' AND policyname = 'weights_service_only'
  ) THEN
    CREATE POLICY "weights_service_only" ON matching_weights
      FOR ALL USING (auth.role() = 'service_role');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'matching_insights' AND policyname = 'insights_service_only'
  ) THEN
    CREATE POLICY "insights_service_only" ON matching_insights
      FOR ALL USING (auth.role() = 'service_role');
  END IF;
END $$;
-- ============================================
-- NANNIES PII REMEDIATION — Full Closure
-- Creates public-safe view for client SDK reads
-- APPLIED: 2026-03-14
-- ============================================

-- 1. Create nannies_public view — strips PII from payload
--    Removes: contact, documents, resumeNormalized
--    Keeps: id, name, photo, city, district, metro, experience, schedule,
--           expectedRate, childAges, skills, about, isVerified, softSkills,
--           videoIntro, video, reviews, riskProfile, isNannySharing, createdAt, type
CREATE OR REPLACE VIEW nannies_public AS
SELECT
  id,
  user_id,
  created_at,
  (payload - 'contact' - 'documents' - 'resumeNormalized') AS payload
FROM nannies;

-- 2. Grant SELECT on the view to authenticated users
GRANT SELECT ON nannies_public TO authenticated;

-- 3. Restrict raw nannies table: only owner can SELECT their own row
--    Drop the broad read policy and replace with owner-only
DROP POLICY IF EXISTS "nannies_read_authenticated" ON nannies;

-- Owner can read their own full profile (for profile editing)
CREATE POLICY "nannies_read_own" ON nannies
  FOR SELECT USING (auth.uid() = user_id);

-- Service role retains full read access (admin, matching engine)
-- (service_role bypasses RLS by default, no explicit policy needed)

-- 4. Verify: the view inherits the base table's RLS for writes,
--    but since it's a SELECT-only view with no INSTEAD OF triggers,
--    writes must go through the nannies table directly (which has
--    own-profile INSERT/UPDATE from Phase 1 migration).
-- ============================================
-- SECURITY REMEDIATION — Red-Team Audit Fixes
-- APPLIED: 2026-03-14
-- ============================================

-- #2 + #3: Fix nannies RLS — allow owner writes, keep public discovery on nannies_public view only
-- Drop Shield 3 policies
DROP POLICY IF EXISTS "nannies_public_read" ON nannies;
DROP POLICY IF EXISTS "nannies_read_authenticated" ON nannies;
DROP POLICY IF EXISTS "nannies_admin_write" ON nannies;

-- Raw table remains owner-only for SELECT.
-- Public discovery must go through public.nannies_public, which strips PII.

-- Nannies can insert their own profile
CREATE POLICY "nannies_own_insert" ON nannies
  FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.role() = 'service_role');

-- Nannies can update their own profile
CREATE POLICY "nannies_own_update" ON nannies
  FOR UPDATE USING (auth.uid() = user_id OR auth.role() = 'service_role');

-- Only service_role can delete nanny profiles
CREATE POLICY "nannies_admin_delete" ON nannies
  FOR DELETE USING (auth.role() = 'service_role');


-- #4: Chat migration conflicts — normalize to `text` column, composite PK
-- Add `text` column if only `content` exists (from migration_v1)
DO $$
BEGIN
  -- If `content` column exists but `text` does not
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chat_messages' AND column_name = 'content'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chat_messages' AND column_name = 'text'
  ) THEN
    ALTER TABLE chat_messages ADD COLUMN text TEXT;
    UPDATE chat_messages SET text = content WHERE text IS NULL;
    ALTER TABLE chat_messages ALTER COLUMN text SET NOT NULL;
    ALTER TABLE chat_messages DROP COLUMN content;
  END IF;

  -- If both exist (partial migration), consolidate
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chat_messages' AND column_name = 'content'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chat_messages' AND column_name = 'text'
  ) THEN
    UPDATE chat_messages SET text = content WHERE text IS NULL AND content IS NOT NULL;
    ALTER TABLE chat_messages DROP COLUMN content;
  END IF;
END $$;

-- Fix chat_participants: ensure composite PK, remove stray `id` column if present
DO $$
BEGIN
  -- If chat_participants has an `id` UUID column (from 20260311 migration)
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'chat_participants' AND column_name = 'id'
  ) THEN
    -- Drop the id-based PK constraint if it exists
    BEGIN
      ALTER TABLE chat_participants DROP CONSTRAINT IF EXISTS chat_participants_pkey;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ALTER TABLE chat_participants DROP COLUMN IF EXISTS id;

    -- Re-add composite PK if missing
    BEGIN
      ALTER TABLE chat_participants ADD PRIMARY KEY (thread_id, user_id);
    EXCEPTION WHEN OTHERS THEN NULL; -- Already exists
    END;
  END IF;
END $$;


-- #5: Fix bookings.request_id type mismatch (TEXT → UUID)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'request_id'
      AND data_type = 'text'
  ) THEN
    -- Drop FK constraint first
    ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_request_id_fkey;
    -- Change type
    ALTER TABLE bookings ALTER COLUMN request_id TYPE UUID USING request_id::uuid;
    -- Re-add FK
    ALTER TABLE bookings ADD CONSTRAINT bookings_request_id_fkey
      FOREIGN KEY (request_id) REFERENCES parents(id);
  END IF;
END $$;


-- #7: Fix payments RLS — restrict to service_role only
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'payments'
  ) THEN
    -- Drop the open policy
    DROP POLICY IF EXISTS "Allow service role full access" ON payments;

    -- Create service-role-only policy
    BEGIN
      CREATE POLICY "payments_service_only" ON payments
        FOR ALL
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
    EXCEPTION WHEN OTHERS THEN NULL; -- Policy might already exist
    END;
  END IF;
END $$;
-- Product analytics events for supply / conversion / retention reporting
-- This mirrors the runtime auto-create path used by api/data.ts for analytics ingest.

CREATE TABLE IF NOT EXISTS analytics_events (
  id TEXT PRIMARY KEY,
  event TEXT NOT NULL,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  url TEXT,
  session_id TEXT,
  user_id TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_event ON analytics_events(event);
CREATE INDEX IF NOT EXISTS idx_analytics_events_occurred_at ON analytics_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events_session_id ON analytics_events(session_id);

COMMENT ON TABLE analytics_events IS 'Product analytics events for Blizko funnels and retention reporting';
-- Allow shadow scoring and interest signals to exist before a final outcome.
ALTER TABLE matching_outcomes
  ALTER COLUMN outcome DROP NOT NULL;

DELETE FROM matching_outcomes older
USING matching_outcomes newer
WHERE older.parent_id = newer.parent_id
  AND older.nanny_id = newer.nanny_id
  AND older.ctid < newer.ctid;

CREATE UNIQUE INDEX IF NOT EXISTS idx_matching_outcomes_parent_nanny_unique
  ON matching_outcomes(parent_id, nanny_id);
-- admin_actions is an internal audit table.
-- Never trust user_metadata for authorization because clients can influence it.

ALTER TABLE IF EXISTS admin_actions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_actions_admin" ON admin_actions;
DROP POLICY IF EXISTS "admin_actions_service_only" ON admin_actions;

CREATE POLICY "admin_actions_service_only" ON admin_actions
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
-- Lock down analytics_events so direct client access is impossible.
-- Writes/reads should only happen through server endpoints using service_role / DB pool.

ALTER TABLE IF EXISTS analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analytics_events_service_only" ON analytics_events;

CREATE POLICY "analytics_events_service_only" ON analytics_events
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
